<?php 
    $this->headTitle('Student Master List');
    
    $this->headLink()->prependStylesheet($this->basePath('assets/datatables/datatables.min.css'));
    $this->inlineScript()
        ->prependFile($this->basePath('assets/datatables/datatables.min.js'))
        ->prependFile($this->basePath('assets/datatables/datatables-buttons.js'));
?>
<section class="content-header">
    <h1>
      Student Master List
      <small>List for all Graduate and Undergraduate Students</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?=$this->url('dashboard'); ?>"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li><a href="<?=$this->url('student');?>"> Student </a></li>
        <li class="active"> History </li>
    </ol>
</section>
<div class="divider"><br></div>       
<section class="content">   
    <!-- Statistics here -->
    
    <!-- End of Statistics -->
    <div class="divider"><hr></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>
                        Master List
                        <small>Full list of all students</small>
                    </h2>
                </div>
                <div class="clearfix"></div>
                <div class="x_content">
                    <table id="datatable-buttons" class="table table-striped table-bordered">
                      <thead>
                        <tr>
                          <th>ID Number</th>
                          <th>First Name</th>
                          <th>Middle Initial</th>
                          <th>Last Name</th>
                          <th>Sex</th>
                          <th>Date of Birth</th>
                          <th>Civil Status</th>
                          <th>Nationality</th>
                          <th>Scholarship</th>
                          <th>Graduate</th>
                        </tr>
                      </thead>
                      <tbody>
                            <?php foreach ($this->students as $student) : ?>
                                <tr>
                                    <td><?=$student['id']?></td>
                                    <td><?=$student['first_name']?></td>
                                    <td><?=$student['middle_name']?></td>
                                    <td><?=$student['last_name']?></td>
                                    <td><?=$student['gender']?></td>
                                    <td><?=$student['date_of_birth']?></td>
                                    <td><?=$student['civil_status']?></td>
                                    <td><?=$student['nationality']?></td>
                                    <td><?=$student['scholarship']?></td>
                                    <td>
                                        <?php
                                            echo ($student['graduate']) ? 'Yes': 'No'
                                        ?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                      </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>