<?php 
    $this->headTitle('Student Admission');
    
//    $this->headLink()->prependStylesheet($this->basePath('assets/datatables/datatables.min.css'));
//    $this->inlineScript()
//        ->prependFile($this->basePath('assets/datatables/datatables.min.js'))
//        ->prependFile($this->basePath('assets/datatables/datatables-buttons.js'));
?>
<section class="content-header">
    <h1>
      Student Admission
      <small>Enlisting of new student</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?=$this->url('dashboard'); ?>"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li class="active"><a href="<?=$this->url('student');?>"> Student Admission </a></li>
    </ol>
</section>
<div class="divider"><br></div>       
<section class="content">
    
</section>